name: "Build Corne Custom"
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_corne_left","splitkb_aurora_corne_right","settings_reset"]'
      kconfig: '["CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y"]'
